### ISSUE TITLE
Wrong Image size of the SCARED dataset in the paper, and Parameter setting for SCARED and SERV-CT

### ISSUE THREAD

**Issue by yzxstore** [JingweiSong/BDIS-v2#1]
Hello, appreciate the release of the code. 

You mentioned that the image size in the SCARED is 1280 × 720 in the paper, which is a mistake. It should be 1280x1024.

Could you please release the setting for SCARED and SERV-CT ?

**Comment by JingweiSong** [comment]
BDIS is a left-right image matching algorithm. It is free of the image size. You can test it on SCARED following the setting in SCARED.

**Comment by JingweiSong** [comment]
Question solved.
