### ISSUE TITLE
prob_out

### ISSUE THREAD

**Issue by sx123456123** [JingweiSong/BDIS-v2#2]
hello! Is the output of prod_out obtained by calculating the optional PDF estimation of the depth? And how can I choose  to turn the optional PDF estimation of the depth on or off?

**Comment by JingweiSong** [comment]
Hi, thanks for the interest. **In general, the input, output and parameter setting are all in src/run_dense.cpp.** I believe the code in the main() function is easy to modify.

Specifically, please comment "string outfile_prob = folderpath + "/" + "prob_out_" + outfilename + filename + ".png";" and related code to turn it off.

Please let me know if this problem has been solved.

**Comment by sx123456123** [comment]
Thank you for reply!	
        param.usefbcon = atoi(argv[acnt++]);
	param.patnorm = atoi(argv[acnt++]);
	param.costfct = atoi(argv[acnt++]);
	param.verbosity = atoi(argv[acnt++]);
	param.ratio_patch_valid = atof(argv[acnt++]);
	param.num_window = atoi(argv[acnt++]);
	param.unit_disturb = atof(argv[acnt++]);
	param.min_prob = atof(argv[acnt++]);
	//if (atof(argv[acnt++]) != 0)
	**param.bool_var = true;**
If I want to turn the optional PDF estimation of the depth off, Is this true changed to false?

**Comment by JingweiSong** [comment]
Yes. But I just noticed I made a mistake on if (param.bool_var){}(Will update the code soon :) ). You can leave "SavePFMFile_prob(probabilityout, outfile_prob.c_str());" in the bracket and keep the rest out of it. By setting param.bool_var as false, variance will not be calculated and the speed can be fastened by around 10%. You may check it out.
